### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by danpeig** [LightAPIs/joplin-copy-code-blocks#5]
Not displaying the copy button in Android.

Note: Plugin is marked as compatible with Android.

**Comment by dragonish** [comment]
TBH, I have not adapted the plugin for mobile. At the same time, I did not specify `platforms` in the plugin manifest. BTW, in [Platforms](https://joplinapp.org/help/api/references/plugin_manifest/#platforms) description, the default is for the desktop only. 🤔

---

I will take time to handle this situation.

**Comment by danpeig** [comment]
Copy from the mobile is a pain. CodePerfect does the copy button right in mobile but the other features it has are undesirable.

If you can figure out a solution for the compatibility problem that would be great.

**Comment by dragonish** [comment]
I debugged the plugin on *Joplin 3.0.5 (prod, android)*, but I could not achieve the desired results. atm, I can only identify the plugin as working for the desktop.

**Comment by personalizedrefrigerator** [comment]
This seems related to an upstream bug in the mobile app's node module emulation. In particular, `module.exports` is incorrectly `null` instead of an empty object. `exports`, however, is correctly defined to be `{}`.
 - Suggestion: Work around this issue by using `exports.default = ...` instead of `module.exports.default = ...` in [copyCodeBlocks.js](https://github.com/LightAPIs/joplin-copy-code-blocks/blob/d819c30dd4b044e007c75798e47205ae5f8a5b46/src/copyCodeBlocks.js#L7). 
 - Upstream, this can be fixed by 1) making `module.exports` default to `{}`, and 2) making `exports` a reference to `module.exports`.
